import {
  Space,
  Mission,
  MemoryItem,
  TabItem,
  NoteItem,
  TaskItem,
  HabitItem,
  CalendarEvent,
  DailyGoal,
  FileItem,
  AgentAction,
  AuditEvent,
  ModelRoute,
  EdgeNode,
  ContainerInfo,
} from "../types";

export const initialSpaces: Space[] = [
  {
    id: "space-dev",
    name: "OM Development",
    icon: "Code2",
    color: "#6366f1", // Indigo
    description: "Core full-stack development workspace, Docker, Express, Vite & Gemini integrations",
    active: true,
    securityPolicy: "strict",
    tabsCount: 4,
    notesCount: 3,
    tasksCount: 5,
    memoryCount: 8,
    lastActiveTime: "Just now",
  },
  {
    id: "space-personal",
    name: "Personal Life & Routine",
    icon: "Compass",
    color: "#10b981", // Emerald
    description: "Habits, health, finance, travel itineraries, daily briefings, and personal notes",
    active: false,
    securityPolicy: "isolated",
    tabsCount: 3,
    notesCount: 4,
    tasksCount: 3,
    memoryCount: 6,
    lastActiveTime: "2 hours ago",
  },
  {
    id: "space-startup",
    name: "Startup & Product",
    icon: "Rocket",
    color: "#f59e0b", // Amber
    description: "Product roadmap, user feedback, pitch deck research, and investor updates",
    active: false,
    securityPolicy: "standard",
    tabsCount: 2,
    notesCount: 2,
    tasksCount: 4,
    memoryCount: 5,
    lastActiveTime: "Yesterday",
  },
  {
    id: "space-homelab",
    name: "Homelab & Infrastructure",
    icon: "Server",
    color: "#ec4899", // Pink
    description: "EdgeNode management, Proxmox VMs, Docker containers, WireGuard mesh VPN",
    active: false,
    securityPolicy: "strict",
    tabsCount: 2,
    notesCount: 2,
    tasksCount: 2,
    memoryCount: 4,
    lastActiveTime: "3 days ago",
  },
];

export const initialMissions: Mission[] = [
  {
    id: "mission-1",
    title: "OM Production Cloud Deployment",
    spaceId: "space-dev",
    goal: "Deploy self-hosted OM instance to Cloud Run with zero-downtime container updates and persistent encrypted volume",
    status: "active",
    progress: 75,
    tasksCount: 4,
    dueDate: "2026-08-15",
  },
  {
    id: "mission-2",
    title: "Sovereign AI Router & Local Ollama Sync",
    spaceId: "space-dev",
    goal: "Setup model router to fallback to Qwen2.5 / DeepSeek R1 local models when offline",
    status: "active",
    progress: 60,
    tasksCount: 3,
    dueDate: "2026-08-18",
  },
  {
    id: "mission-3",
    title: "Personal Q3 Finance & Investment Plan",
    spaceId: "space-personal",
    goal: "Review subscription renewals, automated savings, and private budget audit",
    status: "active",
    progress: 40,
    tasksCount: 3,
    dueDate: "2026-08-30",
  },
];

export const initialMemory: MemoryItem[] = [
  {
    id: "mem-1",
    content: "Decision: Standardized Express backend on port 3000 with esbuild server bundling for single CJS output.",
    entityTags: ["architecture", "express", "esbuild", "node"],
    confidence: 0.98,
    source: "OM Developer Agent",
    scope: "space",
    spaceId: "space-dev",
    createdAt: "2026-08-10 10:15",
    userEditable: true,
    decisionFlag: true,
  },
  {
    id: "mem-2",
    content: "Decision: Use @google/genai SDK with User-Agent 'aistudio-build' header for server-side Gemini 3.6 Flash calls.",
    entityTags: ["gemini", "ai-sdk", "security"],
    confidence: 0.99,
    source: "OM Developer Agent",
    scope: "space",
    spaceId: "space-dev",
    createdAt: "2026-08-10 11:30",
    userEditable: true,
    decisionFlag: true,
  },
  {
    id: "mem-3",
    content: "User Preference: Prefers high-contrast dark/slate visual hierarchy with subtle emerald accent indicators for active statuses.",
    entityTags: ["ui", "theme", "preference"],
    confidence: 0.95,
    source: "OM Personal Memory",
    scope: "private",
    createdAt: "2026-08-09 14:00",
    userEditable: true,
    decisionFlag: false,
  },
  {
    id: "mem-4",
    content: "EdgeNode Configuration: Home server running Proxmox VE at 192.168.1.150 with WireGuard Mesh active.",
    entityTags: ["homelab", "edgenode", "vpn", "network"],
    confidence: 0.96,
    source: "OM Guardian Agent",
    scope: "space",
    spaceId: "space-homelab",
    createdAt: "2026-08-08 18:22",
    userEditable: true,
    decisionFlag: false,
  },
  {
    id: "mem-5",
    content: "Decision: Local Ollama model router defaults to offline fallback gracefully without breaking UI reactivity.",
    entityTags: ["ollama", "local-ai", "resilience"],
    confidence: 0.97,
    source: "OM Guide Agent",
    scope: "space",
    spaceId: "space-dev",
    createdAt: "2026-08-10 12:00",
    userEditable: true,
    decisionFlag: true,
  },
];

export const initialTabs: TabItem[] = [
  {
    id: "tab-1",
    spaceId: "space-dev",
    title: "OM Master Blueprint — Sovereign AI Architecture",
    url: "https://om.ai/docs/master-blueprint",
    isActive: true,
    pinned: true,
    readerMode: false,
    summary: "Complete blueprint for building OM: a private, AI-native operating universe for power users.",
    contentSnippet: "OM unifies browser, search, tabs, spaces, files, notes, tasks, calendar, email, meetings, code, terminal, containers, and personal memory into one persistent context.",
  },
  {
    id: "tab-2",
    spaceId: "space-dev",
    title: "@google/genai TypeScript SDK Docs",
    url: "https://ai.google.dev/docs/genai-sdk",
    isActive: false,
    pinned: true,
    readerMode: false,
    summary: "Official guidance for server-side Gemini 3.6 Flash, 3.5 Flash, and 3.1 Pro Preview integrations.",
    contentSnippet: "Initialize GoogleGenAI server-side with process.env.GEMINI_API_KEY. Use model gemini-3.6-flash for general tasks and gemini-3.1-pro-preview for complex reasoning.",
  },
  {
    id: "tab-3",
    spaceId: "space-dev",
    title: "Docker Compose & Cloud Run Container Spec",
    url: "https://docker.com/docs/compose/cloudrun",
    isActive: false,
    pinned: false,
    readerMode: true,
    summary: "Optimizing multi-stage Docker builds for Node ESM / CJS execution on Cloud Run.",
    contentSnippet: "Ensure port 3000 is bound to 0.0.0.0. Expose health check endpoint at /api/health for zero-downtime container rotation.",
  },
  {
    id: "tab-4",
    spaceId: "space-personal",
    title: "Calm Productivity & Digital Minimalist Workflows",
    url: "https://calmtech.org/articles/calm-productivity",
    isActive: true,
    pinned: true,
    readerMode: true,
    summary: "Principles for quiet software that respects attention, reduces app switching, and restores context.",
    contentSnippet: "Technology should require the smallest possible amount of attention. Inform and create calm rather than anxiety.",
  },
];

export const initialNotes: NoteItem[] = [
  {
    id: "note-1",
    spaceId: "space-dev",
    title: "OM 100 Architectural Principles",
    content: `# OM Architectural Core
1. Context Restoration: Open OM and continue your life — not just an app.
2. Sovereignty: User owns models, memory, machines, and rules.
3. Graceful Fallback: Local AI and cloud services fail gracefully without breaking the core shell.
4. Granular Permissions: Every consequential agent action undergoes risk analysis (READ, DRAFT, ASK, ACT).
5. Mathematical Memory: Entities, timestamps, sources, and scopes for all saved context.`,
    tags: ["architecture", "principles", "om100"],
    updatedAt: "2026-08-10 12:45",
  },
  {
    id: "note-2",
    spaceId: "space-dev",
    title: "Express Backend Route Checklist",
    content: `- [x] GET /api/health
- [x] POST /api/ai/briefing
- [x] POST /api/ai/universal-search
- [x] POST /api/ai/ask-page
- [x] POST /api/ai/agent-task
- [x] POST /api/ai/diagnose-log
- [x] GET /api/ollama/status`,
    tags: ["backend", "express", "api"],
    updatedAt: "2026-08-10 13:10",
  },
  {
    id: "note-3",
    spaceId: "space-personal",
    title: "Morning Routine & Focus Stack",
    content: `1. Open OM -> "Good Morning, OM" Briefing
2. Review top 3 priority tasks
3. 25-min deep focus session in OM Development Space
4. Check Guardian security alerts & EdgeNode health`,
    tags: ["habits", "routine", "mindset"],
    updatedAt: "2026-08-09 08:30",
  },
];

export const initialTasks: TaskItem[] = [
  {
    id: "task-1",
    spaceId: "space-dev",
    missionId: "mission-1",
    title: "Verify Express server health endpoint on port 3000",
    completed: true,
    priority: "p1",
    dueDate: "2026-08-10",
    category: "DevOps",
  },
  {
    id: "task-2",
    spaceId: "space-dev",
    missionId: "mission-1",
    title: "Test Gemini 3.6 Flash universal search with web grounding",
    completed: true,
    priority: "p1",
    dueDate: "2026-08-11",
    category: "AI Integration",
  },
  {
    id: "task-3",
    spaceId: "space-dev",
    missionId: "mission-2",
    title: "Configure local Ollama fallback status handler",
    completed: true,
    priority: "p2",
    dueDate: "2026-08-12",
    category: "Local AI",
  },
  {
    id: "task-4",
    spaceId: "space-dev",
    missionId: "mission-1",
    title: "Audit agent approval risk engine (READ, DRAFT, ASK, ACT)",
    completed: false,
    priority: "p1",
    dueDate: "2026-08-13",
    category: "Security",
  },
  {
    id: "task-5",
    spaceId: "space-personal",
    title: "Review monthly recurring software subscriptions",
    completed: false,
    priority: "p2",
    dueDate: "2026-08-15",
    category: "Finance",
  },
];

export const initialFiles: FileItem[] = [
  {
    id: "file-1",
    spaceId: "space-dev",
    name: "om-architecture-v1.json",
    size: "48 KB",
    type: "application/json",
    path: "/vault/config/om-architecture-v1.json",
    encrypted: true,
    updatedAt: "2026-08-10 11:00",
    contentSnippet: `{"version": "1.0.0", "sovereigntyMode": "hybrid", "storage": "encrypted_local"}`,
  },
  {
    id: "file-2",
    spaceId: "space-dev",
    name: "server-diagnostics-log.txt",
    size: "124 KB",
    type: "text/plain",
    path: "/logs/server-diagnostics-log.txt",
    encrypted: false,
    updatedAt: "2026-08-10 12:30",
    contentSnippet: `[OM-SERVER] GET /api/health 200 OK - 1.2ms
[OM-SERVER] Gemini 3.6 Flash client initialized with aistudio-build header.`,
  },
  {
    id: "file-3",
    spaceId: "space-homelab",
    name: "wireguard-mesh-keys.asc",
    size: "4 KB",
    type: "application/pgp-keys",
    path: "/vault/keys/wireguard-mesh-keys.asc",
    encrypted: true,
    updatedAt: "2026-08-08 19:40",
  },
];

export const initialActions: AgentAction[] = [
  {
    id: "act-1",
    agentName: "Developer Agent",
    title: "Rebuild & bundle server.ts with esbuild for CJS production distribution",
    type: "deployment",
    riskLevel: "ASK",
    command: "npm run build && node dist/server.cjs",
    details: "Compiles TypeScript server entry point and verifies dist/server.cjs output.",
    status: "pending",
    timestamp: "10 mins ago",
    spaceId: "space-dev",
  },
  {
    id: "act-2",
    agentName: "Guardian Agent",
    title: "Rotate EdgeNode WireGuard session keys & verify zero-trust vault access",
    type: "terminal",
    riskLevel: "ASK",
    command: "om-vault rotate-keys --node home-server-1",
    details: "Ensures encrypted peer-to-peer mesh credentials are fresh.",
    status: "pending",
    timestamp: "25 mins ago",
    spaceId: "space-homelab",
  },
  {
    id: "act-3",
    agentName: "Organizer Agent",
    title: "Archive 3 inactive browser tabs & consolidate memory decisions",
    type: "memory",
    riskLevel: "ACT",
    command: "om-browser archive --idle-hours 48",
    details: "Freed 180MB RAM by putting background tabs to sleep.",
    status: "executed",
    timestamp: "1 hour ago",
    spaceId: "space-dev",
  },
];

export const initialAuditEvents: AuditEvent[] = [
  {
    id: "audit-1",
    timestamp: "2026-08-10 13:15:02",
    actor: "Febin (Owner)",
    agent: "Developer Agent",
    tool: "express.startServer",
    action: "Mounted Express server on port 3000 with Vite middleware",
    target: "http://0.0.0.0:3000",
    result: "success",
    riskLevel: "READ",
  },
  {
    id: "audit-2",
    timestamp: "2026-08-10 12:45:20",
    actor: "OM Guide Agent",
    agent: "OM Guide",
    tool: "memory.store",
    action: "Recorded decision regarding @google/genai SDK standard",
    target: "Personal Memory Vault",
    result: "success",
    riskLevel: "ACT",
  },
  {
    id: "audit-3",
    timestamp: "2026-08-10 11:30:10",
    actor: "Febin (Owner)",
    agent: "Guardian Agent",
    tool: "vault.checkPermissions",
    action: "Validated zero-knowledge vault access policies",
    target: "Vault Storage",
    result: "success",
    riskLevel: "READ",
  },
];

export const initialModelRoutes: ModelRoute[] = [
  {
    id: "model-1",
    name: "Gemini 3.6 Flash (Primary)",
    provider: "gemini",
    role: "fast_chat",
    status: "active",
    latencyMs: 180,
    privacyRating: "Encrypted Cloud",
  },
  {
    id: "model-2",
    name: "Gemini 3.1 Pro Preview (High Thinking)",
    provider: "gemini",
    role: "thinking",
    status: "active",
    latencyMs: 450,
    privacyRating: "Encrypted Cloud",
  },
  {
    id: "model-3",
    name: "Ollama Qwen 2.5 7B (Local Fallback)",
    provider: "ollama",
    role: "fast_chat",
    status: "offline",
    latencyMs: 35,
    privacyRating: "Strict Local",
  },
  {
    id: "model-4",
    name: "DeepSeek R1 8B (Local Thinking)",
    provider: "ollama",
    role: "thinking",
    status: "offline",
    latencyMs: 90,
    privacyRating: "Strict Local",
  },
];

export const initialEdgeNodes: EdgeNode[] = [
  {
    id: "node-1",
    name: "OM EdgeNode Home (Proxmox VE)",
    type: "Homelab Server",
    status: "online",
    ipAddress: "192.168.1.150",
    gpuInfo: "NVIDIA RTX 4070 (12GB VRAM)",
    ramUsage: "18.4 / 64 GB (28%)",
    lastSeen: "12s ago",
  },
  {
    id: "node-2",
    name: "Workstation Edge (Windows + WSL2)",
    type: "Laptop Edge",
    status: "online",
    ipAddress: "127.0.0.1",
    gpuInfo: "NVIDIA RTX 3080 Mobile",
    ramUsage: "12.1 / 32 GB (37%)",
    lastSeen: "Just now",
  },
  {
    id: "node-3",
    name: "OM Private VPS Relay (Hetzner)",
    type: "Private VPS",
    status: "online",
    ipAddress: "159.69.88.210",
    ramUsage: "2.8 / 8 GB (35%)",
    lastSeen: "45s ago",
  },
];

export const initialContainers: ContainerInfo[] = [
  {
    id: "cont-1",
    name: "om-web-app",
    image: "om-personal-cloud:v1.0.0",
    status: "running",
    ports: "0.0.0.0:3000->3000/tcp",
    cpu: "1.2%",
    memory: "184 MiB",
    uptime: "2 hours",
  },
  {
    id: "cont-2",
    name: "om-ollama-engine",
    image: "ollama/ollama:latest",
    status: "stopped",
    ports: "127.0.0.1:11434->11434/tcp",
    cpu: "0.0%",
    memory: "0 MiB",
    uptime: "Stopped (Fallback active)",
  },
  {
    id: "cont-3",
    name: "om-vault-daemon",
    image: "hashicorp/vault:latest",
    status: "running",
    ports: "127.0.0.1:8200->8200/tcp",
    cpu: "0.4%",
    memory: "42 MiB",
    uptime: "5 days",
  },
];

export const initialHabits: HabitItem[] = [
  {
    id: "habit-1",
    spaceId: "space-personal",
    title: "Morning OM Review & Briefing",
    category: "Mindset",
    frequency: "daily",
    streak: 12,
    bestStreak: 18,
    completedToday: true,
    history: {
      "2026-08-10": true,
      "2026-08-09": true,
      "2026-08-08": true,
      "2026-08-07": true,
      "2026-08-06": true,
      "2026-08-05": true,
      "2026-08-04": true,
    },
    linkedTaskId: "task-3",
    createdAt: "2026-07-01",
  },
  {
    id: "habit-2",
    spaceId: "space-dev",
    title: "Daily Docker & Code Review",
    category: "Engineering",
    frequency: "weekdays",
    streak: 7,
    bestStreak: 14,
    completedToday: true,
    history: {
      "2026-08-10": true,
      "2026-08-08": true,
      "2026-08-07": true,
      "2026-08-06": true,
      "2026-08-05": true,
    },
    linkedTaskId: "task-1",
    createdAt: "2026-07-15",
  },
  {
    id: "habit-3",
    spaceId: "space-personal",
    title: "30-Min Physical Health & Stretches",
    category: "Health",
    frequency: "daily",
    streak: 5,
    bestStreak: 10,
    completedToday: false,
    history: {
      "2026-08-09": true,
      "2026-08-08": true,
      "2026-08-07": true,
      "2026-08-06": true,
      "2026-08-05": true,
    },
    createdAt: "2026-07-20",
  },
  {
    id: "habit-4",
    spaceId: "space-dev",
    title: "Memory Vault Knowledge Pruning",
    category: "Sovereignty",
    frequency: "daily",
    streak: 3,
    bestStreak: 9,
    completedToday: false,
    history: {
      "2026-08-09": true,
      "2026-08-08": true,
      "2026-08-07": true,
    },
    createdAt: "2026-08-01",
  },
];

export const initialCalendarEvents: CalendarEvent[] = [
  {
    id: "evt-1",
    title: "OM Core Production Architecture Sync",
    time: "10:30 AM - 11:15 AM",
    date: "Today",
    joinUrl: "https://meet.google.com/om-arch-sync",
    attendees: ["alex@om.ai", "febin@om.ai", "lead-dev@om.ai"],
    location: "Google Meet",
    spaceId: "space-dev",
    category: "Architecture",
  },
  {
    id: "evt-2",
    title: "Zero-Knowledge Vault Security Audit",
    time: "02:00 PM - 02:45 PM",
    date: "Today",
    joinUrl: "https://zoom.us/j/9876543210",
    attendees: ["security-guardian@om.ai", "febin@om.ai"],
    location: "Zoom Video",
    spaceId: "space-dev",
    category: "Security",
  },
  {
    id: "evt-3",
    title: "Weekly EdgeNode Mesh Topology Planning",
    time: "11:00 AM - 12:00 PM",
    date: "Tomorrow",
    joinUrl: "https://meet.google.com/om-edge-mesh",
    attendees: ["devops@om.ai", "infrastructure@om.ai"],
    location: "Google Meet",
    spaceId: "space-personal",
    category: "Infrastructure",
  },
];

export const initialDailyGoals: DailyGoal[] = [
  {
    id: "goal-1",
    title: "Verify Docker Container Local Build & API Health",
    completed: true,
    spaceId: "space-dev",
    linkedTaskId: "task-1",
    category: "High Impact",
  },
  {
    id: "goal-2",
    title: "Complete 12-day Habit Streak & Mindset Review",
    completed: true,
    spaceId: "space-personal",
    linkedHabitId: "habit-1",
    category: "Personal Growth",
  },
  {
    id: "goal-3",
    title: "Finalize Zero-Knowledge Vault Export Architecture",
    completed: false,
    spaceId: "space-dev",
    linkedTaskId: "task-2",
    category: "Mission Milestone",
  },
];
